Majid/workload add missing
controlplane-com/terraform-provider-cpln pull request #60
Opened 2024-01-06 01:47 UTC by MajidAbuRmila

2024-02-07 06:01 UTC, enk21 requested changes
I made a commit with a few updates. Kyle, Dan said you can describe the "Parallel" scaling policy in the workload rollout options. In my test workloads, I don't see the following in the status: "health_check", "current_replica_count", "resolved_images".  I am waiting for a response from Dan if these are still work in progress, unless you have a workload you can send me a link for.

2024-02-07 15:19 UTC, Cuppojoe commented on docs/resources/workload.md
> +- **recovery_policy** (String) Only applicable to persistent volumes, this determines what Control Plane will do when creating a new workload replica if a corresponding volume exists. Available Value
We can leave recovery_policy, but please add a deprecated warning. This field is no longer used.

2024-02-07 15:19 UTC, Cuppojoe commented on docs/resources/workload.md
> +- **recovery_policy** (String) Only applicable to persistent volumes, this determines what Control Plane will do when creating a new workload replica if a corresponding volume exists. Available Value
@MajidAbuRmila

2024-02-07 15:23 UTC, Cuppojoe commented
@enk21 The Parallel scaling policy will cause all pods affected by a scaling operation to be created or destroyed simultaneously. This does not affect update operations.

2024-02-07 15:25 UTC, Cuppojoe commented
@enk21 

- health_check: I'm not sure what this one is
- current_replica_count: ditto
- resolved_images: this one only appears if you have enabled dynamic tags on the workload.

2024-02-15 19:02 UTC, enk21 approved these changes

2024-02-15 19:02 UTC, merged